### ISSUE TITLE
Sau khi trao đổi debug về phía khách hàng IT devops, thì mình mới phát hiện ra là do các bạn lại cấu hình Guacamole Server có phần configure RDP tới 1 VM Windows 7/10/11 / 2k19/2k22  là Workgroup không có dùng CA Server để cấp SSL/TLS cho RDP port 3389.

### ISSUE THREAD

**Issue by PhDLeToanThang** [PhDLeToanThang/guacamole#3]
Sau khi trao đổi debug về phía khách hàng IT devops, thì mình mới phát hiện ra là do các bạn lại cấu hình Guacamole Server có phần configure RDP tới 1 VM Windows 7/10/11 / 2k19/2k22  là Workgroup không có dùng CA Server để cấp SSL/TLS cho RDP port 3389.

Mấu chốt là: không có SSL/TLS thì mục Security mode: chỉ dùng được với Any  (nghĩa là tự động nhận dạng RDP client): 

![image](https://github.com/PhDLeToanThang/guacamole/assets/106635733/b628878d-2278-4ed5-8418-ab12b0007f99)

Những kiểu Security mode: khác như: Remote RDP Encryption hoặc NLA là không áp dụng được.

Do vậy, các bạn có thể tham khảo cách tạo Cert SSL/TLS cho RDP
Bài viết: [Cấu hình CA Server tạo Cert SSL/TLS cho RDP 3389 sử dụng Network Level Authenticaton khi Remote](https://thangletoan.wordpress.com/2023/09/04/cau-hinh-ca-server-tao-cert-ssl-tls-cho-rdp-3389-su-dung-network-level-authenticaton-khi-remote/)

_Originally posted by @PhDLeToanThang in https://github.com/PhDLeToanThang/guacamole/issues/1#issuecomment-2039225357_

**Comment by dongnpvn** [comment]
Thanks so much @PhDLeToanThang, this guide worked well for us
